apiVersion: 1

datasources:
  - name: grocr
    type: postgres
    url: db:5432
    database: grocery
    user: grocery
    secureJsonData:
      password: grocery
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    isDefault: true
